% ---------------------------------------------------------
%        PRE-PROCESSING
%---------------------------------------------------------
%
%  In the rotor cage of the Induction Motor current are induced by the stator.
%  The rotor replies to the stator field with an MMF which has the same number of poles
%  as the inducing field, and it is synchronous with it. 
%  The rotor bar current phasors are displaced by an angle equal to the
%  electric rotor slot angle. Often the number of rotor phases is considered
%  equal to the number of rotor slots. However, from a stator point of
%  view, the rotor behaviour is the same as that generated by a three phases winding,
%  with a proper distribution of conductors in the rotor slots.
%  
%  We may assume that in the equivalent three phases winding, the conductors 
%  of each phases are sinusoidally distributed in the rotor slots.
%  The higher the number of rotor slots, the more sinusoidal the current distribution.
%  Each rotor slot results to be filled with a portion of each phase winding.
%  
%  Alternatively, instead of using the three phases equivalent winding, it is
%  possible to adopt an equivalent two-phases winding. 
%  As in the previous equivalence, each phase winding may be considered to be
%  sinusoidally distributed and to produce the same MMF waveform of the original
%  rotor cage, according to the same stator current excitation.
%  The two-phase winding agrees with the three-phase winding when the number of turns 
%  is (3/2) the number of turns of the three-phase winding.
%   
%  For the analysis in the rotor reference frame, it is advantageous to use the two
%  phases equivalent winding, with the two magnetic axes along the direct (d) and 
%  quadrature (q) axes.
%   
%  First of all, it is necessary to know the rotor winding factor. 
%  Remembering that it is assumed that each phase winding is sinusoidally distributed, 
%  so that the MMF waveform exhibit almost a sinusoidal behaviour. 
%  Since the amplitude of the first harmonic of the MMF overlaps the value of the 
%  MMF wave itself, the winding factor is equal to (pi/4).

Qs = stator.Q;              % number of stator slots
ms = stator.winding.m;      % stator winding's number of phases
p = stator.p;               % stator winding's number of pole pairs
qs = Qs/(ms*2*p);           % stator slots per pole per phase
nc = stator.winding.nc;     % conductors pwer slot
npp = stator.winding.npp;   % parallel paths
ncs = nc/npp;               % number of series conductors per slot
Ns = 2*p*ncs*qs;            % number of series conductors per stator phase
alpha_ssm = 2*pi/Qs;        % stator mechanical slot angle
alpha_sse = alpha_ssm*p;    % stator electrical slot angle

Qr = rotor.Q;               % number of rotor slots
alpha_srm = 2*pi/Qr;        % stator mechanical slot angle
alpha_sre = alpha_srm*p;    % stator electrical slot angle

K_S = stator.winding.K_S;

S_emfRe_slot = zeros(1,Qs);
S_emfIm_slot = zeros(1,Qs);

for h = 1:1:Qs
    S_emfRe_slot(h) = K_S(h,1)*cos(alpha_sse/2 + alpha_sse*(h-1));
    S_emfIm_slot(h) = K_S(h,1)*sin(alpha_sse/2 + alpha_sse*(h-1));
end

S_emfRe_tot = sum((S_emfRe_slot));
S_emfIm_tot = sum((S_emfIm_slot));
S_emf_tot   = sqrt(S_emfRe_tot^2 + S_emfIm_tot^2);

S_geom_sum  = S_emf_tot;
S_arith_sum = sum(abs(K_S(:,1)));
K_ws        = S_geom_sum/S_arith_sum;
stator.winding.K_w = K_ws;

% It is needed to distribute sinusoidally this amount of conductors in the
% rotor slots, so as to define a two-phase winding. The two phases of
% the rotor winding have the magnetic axes overlapped with the d- and q-axis.
% For instance, starting from the rotor slot number one, lying on the
% positive direction of the q-axis, in order to define the slot matrix of a
% sinusoidally distributed winding with the magnetic axis along the d-axis.
% The higher dentity of conductors is situated close to the q-axis, and 
% it is decreasing  moving towards the d-axis, the magnetic axis of the
% field distribution.

K_rd = zeros(Qr,1);
K_rq = zeros(Qr,1);

for i = 1:1:Qr
    K_rd(i) = sin(alpha_sre/2 + alpha_sre*(i-1));
end

% The minus before the cosine takes into account that the current in the
% slots above the d-axis has to be incoming in the section, and the current
% in the slots under the d-axis has to be outgoing from the surface.
  
% The winding in quadrature with respect the previous one has the magnetic
% axis overlapped with the q-axis. We start to define the slot matrix from
% the same slot as before, but using a sine function.

for j=1:1:Qr
    K_rq(j) = sin(alpha_sre/2 + alpha_sre*(j-1)-(pi/2)/p);
end

K_slot_matrix_rot_dq = [K_rd K_rq];
%  save('K_slot_matrix_rot_dq.txt','K_slot_matrix_rot_dq','-ASCII')    % TOGLIERE: SOSTITUITA
save('-ascii', 'K_slot_matrix_rot_dq.txt','K_slot_matrix_rot_dq')      % salva
rotor.winding.K_Rdq = load('K_slot_matrix_rot_dq.txt');                % rilegge ??
K_Rdq = rotor.winding.K_Rdq;

% The following calculation lead to know the distribution factor of the 
% rotor winding, whose conductors are almost sinusoidally distributed along
% the air gap.
  
% First of all, it has to calculate the real and immaginary part of the
% induced voltage phasors in each rotor slot, belonging to a certain phase. 
% Remember that each phase fills every rotor slot, with a different number
% of conductors. Let's imagine that, for each slot, the amplitude of the EMF
% is equal to the corresponding coefficient of the two-phase rotor slot
% matrix. EMF phasors are displaced each other by an angle equal to the 
% electrical rotor slot angle.

R_emfRe_slot = zeros(1,Qr);
R_emfIm_slot = zeros(1,Qr);

for hh = 1:1:Qr
    R_emfRe_slot(hh) = K_Rdq(hh,1)*cos(alpha_sre/2 + alpha_sre*(hh-1));
    R_emfIm_slot(hh) = K_Rdq(hh,1)*sin(alpha_sre/2 + alpha_sre*(hh-1));
end
    
% Getting the two components of the total phase EMF as sum os as many EMF
% phasors as rotor slots:

R_emfRe_tot = sum((R_emfRe_slot));
R_emfIm_tot = sum((R_emfIm_slot));
R_emf_tot = sqrt(R_emfRe_tot^2 + R_emfIm_tot^2);

% By means of the previous calculation we got the geometric sum of the EMF
% phasors induced in the conductors in each slot belonging to one phase of
% the rotor winding.

R_geom_sum = R_emf_tot;

% In order to calculate the distribution coefficient of the rotor winding we
% have to know even the arithmetic sum of the emf amplitudes. Remembering
% that the amplitus are equal to the slot matrix coefficients, we have:

R_arith_sum = sum(abs(K_Rdq(:,1)));

K_wr = R_geom_sum/R_arith_sum;
rotor.winding.K_w = K_wr;

% Now we have to know how many conductors there are in each rotor slot. So
% we have to calculate the number of conductors ncr than, multiplied for the
% right slot matrix coefficient, can allow us to know how many conductor we
% have in each slot, belonging to phase d or q.

% We want to treat the rotor as a common two phases winding, wounded into
% the rotor slots. We assume that the rotor and the stator windings, fed
% with the same current, produce two MMF waves with the same amplitude of
% the first harmonic. 
% So, by means of the MMF balancing between stator and rotor we can compute 
% the total number of series conductors in the rotor winding:

Nr2 = ms*K_ws*Ns/(2*K_wr);

% The number of slot per pole per phase is equal to Qr/(2p), in a
% sinusoidally distributed winding in the rotor. The amplitude of the MMF is
% proportional to the number of conductors per pole and per phase.
% The sum of the conductors, which determine the MMF amplitude, is equal to
% Nr/(2p).

ncr2 = Nr2/(2*p)/(sum(abs(K_Rdq(:,1))/(2*p)));

% We can build also the equivalent three phases winding to the rotor cage.
% In this case, assuming to have the same phase current in the rotor and
% in the stator, the number of rotor conductors is carried out as follows:

Nr3 = Ns*(K_ws/K_wr);    questo mi interenssa xk considera 3 fase

% Now compute the slot matrix for the three phase rotor winding:

K_ra = zeros(Qr,1);
K_rb = zeros(Qr,1);
K_rc = zeros(Qr,1);

for i = 1:1:Qr
    K_ra(i) = sin(alpha_sre/2 + alpha_sre*(i-1));
end

for i = 1:1:Qr
    K_rb(i) = sin(alpha_sre/2 + alpha_sre*(i-1)-(2*pi/3));
end

for i = 1:1:Qr
    K_rc(i) = sin(alpha_sre/2 + alpha_sre*(i-1)-(4*pi/3));
end

K_slot_matrix_rot_abc = [K_ra K_rb K_rc];
save('-ascii', 'K_slot_matrix_rot_abc.txt','K_slot_matrix_rot_abc')

rotor.winding.K_Rabc = load('K_slot_matrix_rot_abc.txt');
K_Rabc = rotor.winding.K_Rabc;

% By means of the slot matrix for the three phase rotor winding, it can be
% calculated ncr3 that, multiplied for each coefficient of the slot matrix,
% allows to know the actual number of conductors in each rotor slots,
% belonging to each phase:

ncr3 = Nr3/(2*p)/(sum(abs(K_Rabc(:,1))/(2*p)));

rotor.winding.m   = 3;
rotor.winding.ncs = ncr3;
rotor.winding.Nr  = Nr3;
